### ISSUE TITLE
Porting to MacOS (AppKit)

### ISSUE THREAD

**Issue by martindufort** [danielsaidi/Tutti#6]
Been searching for an Onboarding library for MacOS and came across yours. 
Question: How easy would it be to port this to MacOS AppKit (10.12+). 

I would be interested in helping.
Let me know - Cheers - Martin

**Comment by danielsaidi** [comment]
Hi Martin! I would love to give this a try. I guess the model should work as is, but the presenter model must probably be completely rewritten. I haven't done any AppKit development, so I'm unsure how to best proceed, but if you'd like to have a go at it, I'd love to be part of the process!

All the best - Daniel

**Comment by danielsaidi** [comment]
Hi @martindufort 

I am excited to try out the new macOS bridging features that will be released with Catalyst this spring. I will investigate this when the betas stabilize and will probably add SwiftUI support pretty close to that as well.

Are you still interested in investigating this?

**Comment by danielsaidi** [comment]
I will do this as part of SwiftUI support.

**Comment by danielsaidi** [comment]
Tutti `3.0` supports iOS, macOS, tvOS and watchOS. Most views are only available in iOS, but the models can be used on all platforms.
