### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by wbdeedcoin** [danielsaidi/Tutti#8]
linker command failed with exit code 1 (use -v to see invocation)

installing this pod broke my project

**Comment by danielsaidi** [comment]
Hi! I'll check and fix asap.

D

Den tis 2 apr. 2019 20:13wbdeedcoin <notifications@github.com> skrev:

**Comment by danielsaidi** [comment]
We are using the latest version in our next release. Which Tutti version do you use? Please note that the latest version is built for Swift 5.

**Comment by wbdeedcoin** [comment]
I had to pod deintegrate. It broke my whole project. 
I have xcode 10.1 and swift 5. 
I cd into project root. 
pod init
and added the pod lines
then ran pod install
And when I relaunched Xcode I got the linker error. 
I'll try again today.
Could you provide a pod example file and dir structure in the install instructions? Maybe I installed wrong.

**Comment by danielsaidi** [comment]
You must use Xcode 10.2 to get Swift 5 support. Using Xcode 10.1 is probably what's causing the problem.
